version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:

    docker:
#      - image: cimg/<language>:<version TAG>
      - image: system-images;android-25;google_apis;x86
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: echo "this is the build job"
  test:
    docker:
#      - image: cimg/<language>:<version TAG>
      - image: system-images;android-25;google_apis;x86
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: echo "this is the test job"

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build

#version: 2.1
#
#orbs:
#  android: circleci/android@1.0.3
#
#jobs:
#  build-and-test:
#    executor:
#      name: android/android-machine
#
#    steps:
#      - checkout
#
#      - android/run-tests:
#          test-command: ./gradlew lint testDebug --continue
#
#      - android/start-emulator-and-run-tests:
#          test-command: ./gradlew connectedDebugAndroidTest
#          system-image: system-images;android-25;google_apis;x86
#
#      - run:
#          name: Assemble release build
#          command: |
#            ./gradlew assembleRelease
#
#workflows:
#  sample:
#    jobs:
#      - build-and-test